### ISSUE TITLE
it seems cool...

### ISSUE THREAD

**Issue by arnou** [Thomah/souvenirs-api#1]
but what should that do ?

someone fork this project in our organization, but we can't remember the purpose 😉

![image](https://github.com/Thomah/souvenirs-api/assets/1025691/9eb6a5ce-d396-4fa9-8d0e-f560a6807e7d)

**Comment by Thomah** [comment]
Hello @arnou ! Sorry did not get the notification :s
The goal was to have a project for the immersion program. Something simple and fun that illustrate the different steps of deploying "as code" in the environment.
Souvenirs is an app I coded in Java / Angular to shows a photo gallery and let the user take new pictures with its webcam.
I thought it was relevant at that time but you're free to use whatever you want of course 😄
